$ python src/async_perturb_test.py model01 1 0
Initializing execution for organism='model01', with filter_states=False, fixed_start_states=False, single_it_cnt=1, double_it_cnt=0...
Avg score for model01 is 3004 for 1 iterations.
For graph_mod='Original Graph', avg_graph_score=3284
For graph_mod='Cdc2014-to-Cln3 -> 0to1', avg_graph_score=16377
For graph_mod='Mcm1,SFF-to-Cln3 -> 0to1', avg_graph_score=14890
For graph_mod='SBF-to-Cln3 -> 0to1', avg_graph_score=12287
For graph_mod='Cln3-to-Cln3 -> -1to0', avg_graph_score=12400
For graph_mod='Cdh1-to-Cln3 -> 0to1', avg_graph_score=3838
For graph_mod='Cln1,2-to-MBF -> 0to1', avg_graph_score=1911
For graph_mod='Clb5,6-to-MBF -> 0to1', avg_graph_score=9753
For graph_mod='Swi5-to-MBF -> 0to1', avg_graph_score=6826
For graph_mod='Sic1-to-Cln3 -> 0to1', avg_graph_score=9486
For graph_mod='Cdc2014-to-SBF -> 0to1', avg_graph_score=10895
For graph_mod='Cln1,2-to-Cln1,2 -> -1to0', avg_graph_score=10061
For graph_mod='Clb1,2-to-MBF -> -1to0', avg_graph_score=9655
For graph_mod='MBF-to-MBF -> 0to1', avg_graph_score=2976
For graph_mod='Cdh1-to-SBF -> 0to1', avg_graph_score=8060
For graph_mod='Mcm1,SFF-to-SBF -> 0to1', avg_graph_score=10632
For graph_mod='SBF-to-SBF -> 0to1', avg_graph_score=3169
For graph_mod='Sic1-to-SBF -> 0to1', avg_graph_score=9076
For graph_mod='Swi5-to-Cln1,2 -> 0to1', avg_graph_score=10418
For graph_mod='Cln3-to-SBF -> 1to0', avg_graph_score=3613
For graph_mod='MBF-to-Cln1,2 -> 0to1', avg_graph_score=2177
For graph_mod='Cdc2014-to-Cln3 -> 0to-1', avg_graph_score=3314
For graph_mod='Cln3-to-Cln3 -> -1to1', avg_graph_score=12472
For graph_mod='Mcm1,SFF-to-Cln3 -> 0to-1', avg_graph_score=3234
For graph_mod='Cdh1-to-Cln3 -> 0to-1', avg_graph_score=3099
For graph_mod='Clb1,2-to-MBF -> -1to1', avg_graph_score=11457
For graph_mod='Cln1,2-to-MBF -> 0to-1', avg_graph_score=4973
For graph_mod='SBF-to-Cln3 -> 0to-1', avg_graph_score=2677
For graph_mod='Cln1,2-to-Cln1,2 -> -1to1', avg_graph_score=9896
For graph_mod='Swi5-to-MBF -> 0to-1', avg_graph_score=4262
For graph_mod='Mcm1,SFF-to-SBF -> 0to-1', avg_graph_score=3129
For graph_mod='MBF-to-MBF -> 0to-1', avg_graph_score=4784
For graph_mod='Sic1-to-SBF -> 0to-1', avg_graph_score=2953
For graph_mod='Sic1-to-Cln3 -> 0to-1', avg_graph_score=3564
For graph_mod='Clb5,6-to-MBF -> 0to-1', avg_graph_score=3416
For graph_mod='Cdc2014-to-SBF -> 0to-1', avg_graph_score=2184
For graph_mod='Cln3-to-SBF -> 1to-1', avg_graph_score=3537
For graph_mod='SBF-to-SBF -> 0to-1', avg_graph_score=3066
For graph_mod='Cdh1-to-SBF -> 0to-1', avg_graph_score=3050
For graph_mod='Swi5-to-Cln1,2 -> 0to-1', avg_graph_score=3415
For graph_mod='MBF-to-Cln1,2 -> 0to-1', avg_graph_score=4474
For graph_mod='Swi5-to-Cln3 -> 0to1', avg_graph_score=16210
For graph_mod='MBF-to-Cln3 -> 0to1', avg_graph_score=13632
For graph_mod='Cln1,2-to-Cln3 -> 0to1', avg_graph_score=12755
For graph_mod='Clb5,6-to-Cln3 -> 0to1', avg_graph_score=10753
For graph_mod='Cln3-to-MBF -> 1to0', avg_graph_score=3736
For graph_mod='Clb1,2-to-SBF -> -1to0', avg_graph_score=10446
For graph_mod='Mcm1,SFF-to-MBF -> 0to1', avg_graph_score=8931
For graph_mod='Cdc2014-to-MBF -> 0to1', avg_graph_score=7933
For graph_mod='Cdh1-to-MBF -> 0to1', avg_graph_score=3889
For graph_mod='Cln3-to-Cln1,2 -> 0to1', avg_graph_score=2539
For graph_mod='SBF-to-MBF -> 0to1', avg_graph_score=1560
For graph_mod='Cln1,2-to-SBF -> 0to1', avg_graph_score=9829
For graph_mod='Cdh1-to-Cln1,2 -> 0to1', avg_graph_score=4192
For graph_mod='Sic1-to-MBF -> 0to1', avg_graph_score=3547
For graph_mod='Clb1,2-to-Cln3 -> 0to1', avg_graph_score=12345
For graph_mod='Clb5,6-to-SBF -> 0to1', avg_graph_score=2957
For graph_mod='Cdc2014-to-Cln1,2 -> 0to1', avg_graph_score=11034
For graph_mod='MBF-to-SBF -> 0to1', avg_graph_score=2191
For graph_mod='Swi5-to-SBF -> 0to1', avg_graph_score=10635
For graph_mod='SBF-to-Cln1,2 -> 1to0', avg_graph_score=3902
For graph_mod='MBF-to-Cln3 -> 0to-1', avg_graph_score=2748
For graph_mod='Cln3-to-MBF -> 1to-1', avg_graph_score=4075
For graph_mod='Swi5-to-Cln3 -> 0to-1', avg_graph_score=2822
For graph_mod='Cln1,2-to-Cln3 -> 0to-1', avg_graph_score=3299
For graph_mod='Clb5,6-to-Cln3 -> 0to-1', avg_graph_score=2742
For graph_mod='Cdh1-to-MBF -> 0to-1', avg_graph_score=3765
For graph_mod='Clb1,2-to-SBF -> -1to1', avg_graph_score=12571
For graph_mod='Mcm1,SFF-to-MBF -> 0to-1', avg_graph_score=3934
For graph_mod='Cdc2014-to-MBF -> 0to-1', avg_graph_score=3364
For graph_mod='Sic1-to-MBF -> 0to-1', avg_graph_score=3517
For graph_mod='Cdc2014-to-Cln1,2 -> 0to-1', avg_graph_score=3477
For graph_mod='Cln1,2-to-SBF -> 0to-1', avg_graph_score=2505
For graph_mod='SBF-to-MBF -> 0to-1', avg_graph_score=5198
For graph_mod='Cln3-to-Cln1,2 -> 0to-1', avg_graph_score=3125
For graph_mod='Cdh1-to-Cln1,2 -> 0to-1', avg_graph_score=3738
For graph_mod='MBF-to-SBF -> 0to-1', avg_graph_score=3733
For graph_mod='Clb1,2-to-Cln3 -> 0to-1', avg_graph_score=3515
For graph_mod='Clb5,6-to-SBF -> 0to-1', avg_graph_score=2747
For graph_mod='Swi5-to-SBF -> 0to-1', avg_graph_score=2378
For graph_mod='SBF-to-Cln1,2 -> 1to-1', avg_graph_score=3836
Exception ignored in: <function Variable.__del__ at 0x0000018A0951DFC0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000018A0951DFC0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000018A0951DFC0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x0000018A0951DFC0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x0000018A09585750>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4056, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

traja@MSI-Raj MINGW64 ~/cellanalysis (rajtest)
$ For graph_mod='Clb1,2-to-Cln1,2 -> 0to1', avg_graph_score=11427
For graph_mod='Clb5,6-to-Cln1,2 -> 0to1', avg_graph_score=2806
For graph_mod='Cln3-to-Cdh1 -> 0to1', avg_graph_score=3300
For graph_mod='SBF-to-Cdh1 -> 0to1', avg_graph_score=3265
For graph_mod='Cdh1-to-Cdh1 -> 0to1', avg_graph_score=3031
For graph_mod='Sic1-to-Cdh1 -> 0to1', avg_graph_score=2316
For graph_mod='Cdc2014-to-Cdh1 -> 1to0', avg_graph_score=3663
For graph_mod='Mcm1,SFF-to-Cdh1 -> 0to1', avg_graph_score=3240
For graph_mod='Clb1,2-to-Cln1,2 -> 0to-1', avg_graph_score=2985
For graph_mod='SBF-to-Cdh1 -> 0to-1', avg_graph_score=2466
For graph_mod='Cln3-to-Cdh1 -> 0to-1', avg_graph_score=3044
For graph_mod='Cdh1-to-Cdh1 -> 0to-1', avg_graph_score=4292
For graph_mod='Sic1-to-Cdh1 -> 0to-1', avg_graph_score=4539
For graph_mod='Clb5,6-to-Cln1,2 -> 0to-1', avg_graph_score=3351
For graph_mod='Cdc2014-to-Cdh1 -> 1to-1', avg_graph_score=4336
For graph_mod='Mcm1,SFF-to-Cdh1 -> 0to-1', avg_graph_score=3189
For graph_mod='Mcm1,SFF-to-Cln1,2 -> 0to1', avg_graph_score=11356
For graph_mod='Clb5,6-to-Cdh1 -> -1to0', avg_graph_score=3532
For graph_mod='Clb1,2-to-Cdh1 -> -1to0', avg_graph_score=2644
For graph_mod='MBF-to-Cdh1 -> 0to1', avg_graph_score=3765
For graph_mod='Sic1-to-Cln1,2 -> 0to1', avg_graph_score=5796
For graph_mod='Swi5-to-Cdh1 -> 0to1', avg_graph_score=3074
For graph_mod='Cln1,2-to-Cdh1 -> -1to0', avg_graph_score=3335
For graph_mod='Cln3-to-Swi5 -> 0to1', avg_graph_score=2722
For graph_mod='Mcm1,SFF-to-Cln1,2 -> 0to-1', avg_graph_score=2496
Process SpawnPoolWorker-46:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='Clb1,2-to-Cdh1 -> -1to1', avg_graph_score=3304
Process SpawnPoolWorker-58:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='Clb5,6-to-Cdh1 -> -1to1', avg_graph_score=3660
Process SpawnPoolWorker-49:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='MBF-to-Cdh1 -> 0to-1', avg_graph_score=2866
Process SpawnPoolWorker-43:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='Swi5-to-Cdh1 -> 0to-1', avg_graph_score=3989
Process SpawnPoolWorker-45:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='Cln1,2-to-Cdh1 -> -1to1', avg_graph_score=5010
Process SpawnPoolWorker-42:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='Sic1-to-Cln1,2 -> 0to-1', avg_graph_score=3808
Process SpawnPoolWorker-41:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
For graph_mod='Cln3-to-Swi5 -> 0to-1', avg_graph_score=2780
Process SpawnPoolWorker-51:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\queues.py", line 374, in put
    self._writer.send_bytes(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
